In [1]:
# import Python packages
import pandas as pd
import numpy as np
#import matplotlib as mlp
#import matplotlib.pyplot as plt
#import seaborn as sns


In [2]:
# Loading the dataset
Cars_df=pd.read_csv("D:/Studies/My Projects/Data Science/Car Prediction/Data/vehicles.csv")
Cars_df.head()

id                                                url  \
0  7222695916  https://prescott.craigslist.org/cto/d/prescott...   
1  7218891961  https://fayar.craigslist.org/ctd/d/bentonville...   
2  7221797935  https://keys.craigslist.org/cto/d/summerland-k...   
3  7222270760  https://worcester.craigslist.org/cto/d/west-br...   
4  7210384030  https://greensboro.craigslist.org/cto/d/trinit...   

                   region                         region_url  price  year  \
0                prescott    https://prescott.craigslist.org   6000   NaN   
1            fayetteville       https://fayar.craigslist.org  11900   NaN   
2            florida keys        https://keys.craigslist.org  21000   NaN   
3  worcester / central MA   https://worcester.craigslist.org   1500   NaN   
4              greensboro  https://greensboro.craigslist.org   4900   NaN   

  manufacturer model condition cylinders  ... size  type paint_color  \
0          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
1          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
2          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
3          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
4          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   

  image_url description county state lat long posting_date  
0       NaN         NaN    NaN    az NaN  NaN          NaN  
1       NaN         NaN    NaN    ar NaN  NaN          NaN  
2       NaN         NaN    NaN    fl NaN  NaN          NaN  
3       NaN         NaN    NaN    ma NaN  NaN          NaN  
4       NaN         NaN    NaN    nc NaN  NaN          NaN  

[5 rows x 26 columns]

In [3]:
# checking for no rows, columns
print("This Dataset {} Rows and {} columns".format(Cars_df.shape[0],Cars_df.shape[1]))

This Dataset 426880 Rows and 26 columns


In [4]:
# printing the full summary of dataset
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            426880 non-null  int64  
 1   url           426880 non-null  object 
 2   region        426880 non-null  object 
 3   region_url    426880 non-null  object 
 4   price         426880 non-null  int64  
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  object 
 7   model         421603 non-null  object 
 8   condition     252776 non-null  object 
 9   cylinders     249202 non-null  object 
 10  fuel          423867 non-null  object 
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  object 
 13  transmission  424324 non-null  object 
 14  VIN           265838 non-null  object 
 15  drive         296313 non-null  object 
 16  size          120519 non-null  object 
 17  type          334022 non-null  object 
 18  pain

In [5]:
# checking the no of unique values for manufacturer
Cars_df['manufacturer'].unique()

array([nan, 'gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa-romeo',
       'subaru', 'acura', 'hyundai', 'mercedes-benz', 'bmw', 'mitsubishi',
       'volkswagen', 'porsche', 'kia', 'rover', 'ferrari', 'mini',
       'pontiac', 'fiat', 'tesla', 'saturn', 'mercury', 'harley-davidson',
       'datsun', 'aston-martin', 'land rover', 'morgan'], dtype=object)

In [6]:
# Checking for Unique Values
Cars_df["model"].unique()

array([nan, 'sierra 1500 crew cab slt', 'silverado 1500', ...,
       'gand wagoneer', '96 Suburban', 'Paige Glenbrook Touring'],
      dtype=object)

In [7]:
# Checking for count of Unique Values
Cars_df["model"].nunique()

29667

In [8]:
# Checking for Unique Values for conditions
Cars_df["condition"].unique()

array([nan, 'good', 'excellent', 'fair', 'like new', 'new', 'salvage'],
      dtype=object)

In [9]:
# Checking for Unique Values for cylinders
Cars_df["cylinders"].unique()

array([nan, '8 cylinders', '6 cylinders', '4 cylinders', '5 cylinders',
       'other', '3 cylinders', '10 cylinders', '12 cylinders'],
      dtype=object)

In [10]:
# checking for Unique values for fuel
Cars_df["fuel"].unique()

array([nan, 'gas', 'other', 'diesel', 'hybrid', 'electric'], dtype=object)

In [11]:
# checking for unique values for odometer
Cars_df["odometer"].unique()

array([    nan,  57923.,  71229., ..., 172511.,  94964.,  26892.])

In [12]:
# checking for unique values for title_status  
Cars_df["title_status"].unique()

array([nan, 'clean', 'rebuilt', 'lien', 'salvage', 'missing',
       'parts only'], dtype=object)

In [13]:
# checking for unique values for drive
Cars_df["VIN"].unique()

array([nan, '3GTP1VEC4EG551563', '1GCSCSE06AZ123805', ...,
       '2HGES15535H620534', '1FDWF37P64EA24868', 'SAJGX2749VCOO8376'],
      dtype=object)

In [14]:
# checking for unique values for drive
Cars_df["drive"].unique()

array([nan, 'rwd', '4wd', 'fwd'], dtype=object)

In [15]:
# checking for unique values for size.
Cars_df["size"].unique()

array([nan, 'full-size', 'mid-size', 'compact', 'sub-compact'],
      dtype=object)

In [16]:
# checking for unique values for type.
Cars_df["type"].unique()
#Cars_df["type"].isnull().sum()

array([nan, 'pickup', 'truck', 'other', 'coupe', 'SUV', 'hatchback',
       'mini-van', 'sedan', 'offroad', 'bus', 'van', 'convertible',
       'wagon'], dtype=object)

In [17]:
# checking for unique values for paint_color   .
Cars_df["paint_color"].unique()

array([nan, 'white', 'blue', 'red', 'black', 'silver', 'grey', 'brown',
       'yellow', 'orange', 'green', 'custom', 'purple'], dtype=object)

## Cleaning Dataset based on features

Here are the notes for cleaning which shoule be considered when cleaning.
- on the Manufacturer column we can see NAN Values. (Dropping those Values since there is no ways getting those values)
- on the  value for price drop if it is 0 (first replace with NP.nan and remove those values)
- on the Model Column we can see NAN Values Dropping those Values since there is no ways getting those values)
- There are almost 30000 unique values,so we have to find a way reduce those no of unique values as first stage we will trt split the Model into core model by considering first two words.
- Np.Nan can be adjusted based on number of years if the car is 0-2 "excellent" 3-6 to "fair", 7-12 to "Good" & more than 12 "salvage"
- remove the np.nan values in cylinder, other.
- remove the "np.nan" values in fuel remove other.
- remove the "np.nan" in odometer
- remove the "np.nan" in Title status
- Drop the VIN number form dataframe (Reason for droping will not help for prediction since all the VIN Values are unique for each cars "17-digit code of letters and numbers that identifies a car uniquely and is assigned at the time a vehicle is manufactured")
- Remove the "np.nan" values for drive.
- Drop the size column.
- Remove the "np.nan" values for type.
- replace the "np.nan" values with maximum.
- drop image url drop description columns from dataframe.
- drop county column since there is no value on that.
- for state Column replace the short name with full name.
- drop lat long columns (we can use to create map with folium based on position)
- Posting date should can be used for creating line chart for understanding when they are selling more cars. drop them after that

After cleaning we can expect arround 200 to 250k of cleaned data points for EDA.

In [18]:
# Getting a backup of dataframe before data manipulation
Backup=Cars_df.copy()

In [19]:
# Checking for total no of null values in full dataset
Cars_df.isnull().sum()

id                   0
url                  0
region               0
region_url           0
price                0
year              1205
manufacturer     17646
model             5277
condition       174104
cylinders       177678
fuel              3013
odometer          4400
title_status      8242
transmission      2556
VIN             161042
drive           130567
size            306361
type             92858
paint_color     130203
image_url           68
description         70
county          426880
state                0
lat               6549
long              6549
posting_date        68
dtype: int64

### Dropping columns from DataFrame

We are dropping following features from the dataframe & Reasons

 - For First Round we are going to cleanout following columns
     - id 
     - VIN Column - VIN is a unique key number given for each car by manufacturer, so it cannot be used as a feature for prediction.
     - url for link ad 
     - Region_url
     - Droping model
     - County column - This column is fully empty so we should remove those
     - size column - This column has 75% of values null.
     - Description - Not required
     - lat - not Required
     - Long - not Required
     - Image Url - Not required
     - state -not required
     - title status - ignored
    
     

In [20]:
# to remove columns df.drop(["XXX"],axis=1)
Cars_df=Cars_df.drop(["id", "url", "region_url","VIN", "county", "size", "description","lat", "long", 
                      "image_url", "paint_color","posting_date", "region", "state", "title_status"], axis=1)


Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   price         426880 non-null  int64  
 1   year          425675 non-null  float64
 2   manufacturer  409234 non-null  object 
 3   model         421603 non-null  object 
 4   condition     252776 non-null  object 
 5   cylinders     249202 non-null  object 
 6   fuel          423867 non-null  object 
 7   odometer      422480 non-null  float64
 8   transmission  424324 non-null  object 
 9   drive         296313 non-null  object 
 10  type          334022 non-null  object 
dtypes: float64(2), int64(1), object(8)
memory usage: 35.8+ MB


In [21]:
#checking for possible dropout values 
Cars_df.isnull().any(axis=1).sum()

297451

### Removing np.nan values from dataframe.

In [22]:
# Price
# replacing the zero value to Np.nan, because the if the price is zero it means it is free for sales.
Cars_df["price"].replace(0,np.nan, inplace=True)
Cars_df["price"].isnull().sum()

32895

In [23]:
# Dropping the null value from prices
Cars_df.dropna(subset=["price"], inplace=True)

In [24]:
Cars_df["price"].isnull().sum()

0

In [25]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 393985 entries, 0 to 426879
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   price         393985 non-null  float64
 1   year          392812 non-null  float64
 2   manufacturer  377800 non-null  object 
 3   model         389284 non-null  object 
 4   condition     242596 non-null  object 
 5   cylinders     233575 non-null  object 
 6   fuel          391391 non-null  object 
 7   odometer      391695 non-null  float64
 8   transmission  392162 non-null  object 
 9   drive         273731 non-null  object 
 10  type          308053 non-null  object 
dtypes: float64(3), object(8)
memory usage: 36.1+ MB


In [26]:
# dropping null values form Year
Cars_df.dropna(subset=["year"], inplace=True)

In [27]:
# dropping null values form manufacturer
Cars_df.dropna(subset=["manufacturer"], inplace=True)

Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 377796 entries, 27 to 426879
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   price         377796 non-null  float64
 1   year          377796 non-null  float64
 2   manufacturer  377796 non-null  object 
 3   model         373157 non-null  object 
 4   condition     232120 non-null  object 
 5   cylinders     224296 non-null  object 
 6   fuel          375629 non-null  object 
 7   odometer      375619 non-null  float64
 8   transmission  376093 non-null  object 
 9   drive         263870 non-null  object 
 10  type          297464 non-null  object 
dtypes: float64(3), object(8)
memory usage: 34.6+ MB


In [28]:
# Replacing conditions null value with following Criteria
# Np.Nan can be adjusted based on number of years if the car is 
#0-2 "excellent" 3-6 to "Good", 7-12 to "fair" & more than 12 "salvage"

Cars_df["years_used"]=2022-Cars_df["year"]
Cars_df["years_used"].head()
Cars_df["years_used"].astype(int)

27         8
28        12
29         2
30         5
31         9
          ..
426875     3
426876     2
426877     2
426878     4
426879     3
Name: years_used, Length: 377796, dtype: int32

In [29]:
# changing null value in condition to years used.

m1 = (Cars_df["condition"].isnull()) & (Cars_df["years_used"]<=2)
m2 = (Cars_df["condition"].isnull()) & (Cars_df["years_used"]>=3) & (Cars_df["years_used"]<=6)
m3 = (Cars_df["condition"].isnull()) & (Cars_df["years_used"]>=7) & (Cars_df["years_used"]<=12)
m4 = (Cars_df["condition"].isnull()) & (Cars_df["years_used"]>12)


Cars_df.loc[m1, "condition"]="excellent"
Cars_df.loc[m2, "condition"]="good"
Cars_df.loc[m3, "condition"]="fair"
Cars_df.loc[m4, "condition"]="salvage"

In [30]:
Cars_df["condition"].unique()

array(['good', 'excellent', 'fair', 'salvage', 'like new', 'new'],
      dtype=object)

In [31]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 377796 entries, 27 to 426879
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   price         377796 non-null  float64
 1   year          377796 non-null  float64
 2   manufacturer  377796 non-null  object 
 3   model         373157 non-null  object 
 4   condition     377796 non-null  object 
 5   cylinders     224296 non-null  object 
 6   fuel          375629 non-null  object 
 7   odometer      375619 non-null  float64
 8   transmission  376093 non-null  object 
 9   drive         263870 non-null  object 
 10  type          297464 non-null  object 
 11  years_used    377796 non-null  float64
dtypes: float64(4), object(8)
memory usage: 37.5+ MB


In [32]:
# Droping the null values in models
Cars_df.dropna(subset=["model"], inplace=True)

In [33]:
Cars_df["model"].head()

27    sierra 1500 crew cab slt
28              silverado 1500
29         silverado 1500 crew
30        tundra double cab sr
31                   f-150 xlt
Name: model, dtype: object

In [34]:
# split the model name and get the first two out of those.
Cars_df["model_updated"]=Cars_df["model"].str.split(" ").str.slice(0,2).str.join(" ")
Cars_df["model_updated"].head()

27       sierra 1500
28    silverado 1500
29    silverado 1500
30     tundra double
31         f-150 xlt
Name: model_updated, dtype: object

In [35]:
Cars_df.head()

price    year manufacturer                     model  condition  \
27  33590.0  2014.0          gmc  sierra 1500 crew cab slt       good   
28  22590.0  2010.0    chevrolet            silverado 1500       good   
29  39590.0  2020.0    chevrolet       silverado 1500 crew       good   
30  30990.0  2017.0       toyota      tundra double cab sr       good   
31  15000.0  2013.0         ford                 f-150 xlt  excellent   

      cylinders fuel  odometer transmission drive    type  years_used  \
27  8 cylinders  gas   57923.0        other   NaN  pickup         8.0   
28  8 cylinders  gas   71229.0        other   NaN  pickup        12.0   
29  8 cylinders  gas   19160.0        other   NaN  pickup         2.0   
30  8 cylinders  gas   41124.0        other   NaN  pickup         5.0   
31  6 cylinders  gas  128000.0    automatic   rwd   truck         9.0   

     model_updated  
27     sierra 1500  
28  silverado 1500  
29  silverado 1500  
30   tundra double  
31       f-150 xlt

In [36]:
Cars_df["manufacturer"]=Cars_df["manufacturer"].str.title()
Cars_df["model"]=Cars_df["model"].str.title()
Cars_df["model_updated"]=Cars_df["model_updated"].str.title()
Cars_df["condition"]=Cars_df["condition"].str.title()
Cars_df["drive"]=Cars_df["drive"].str.title()
Cars_df["transmission"]=Cars_df["transmission"].str.title()
Cars_df["fuel"]=Cars_df["fuel"].str.title()
Cars_df["type"]=Cars_df["type"].str.title()
Cars_df.head()

price    year manufacturer                     model  condition  \
27  33590.0  2014.0          Gmc  Sierra 1500 Crew Cab Slt       Good   
28  22590.0  2010.0    Chevrolet            Silverado 1500       Good   
29  39590.0  2020.0    Chevrolet       Silverado 1500 Crew       Good   
30  30990.0  2017.0       Toyota      Tundra Double Cab Sr       Good   
31  15000.0  2013.0         Ford                 F-150 Xlt  Excellent   

      cylinders fuel  odometer transmission drive    type  years_used  \
27  8 cylinders  Gas   57923.0        Other   NaN  Pickup         8.0   
28  8 cylinders  Gas   71229.0        Other   NaN  Pickup        12.0   
29  8 cylinders  Gas   19160.0        Other   NaN  Pickup         2.0   
30  8 cylinders  Gas   41124.0        Other   NaN  Pickup         5.0   
31  6 cylinders  Gas  128000.0    Automatic   Rwd   Truck         9.0   

     model_updated  
27     Sierra 1500  
28  Silverado 1500  
29  Silverado 1500  
30   Tundra Double  
31       F-150 Xlt

In [37]:
Values=["Cc",
"3 I",
"Deisel Cummins",
"Dealer* Luxury",
"Cayenne 1-Owner*",
"6",
"Diesel Cummins",
"7000",
"912",
"2",
"3500 Diesel",
"940",
"3100",
"530",
"4400",
"245",
"914",
"740",
"300 'L'",
"68",
"C -",
"850",
"86",
"350",
"240",
"370",
"3200",
"300 K",
"528",
"745",
"720",
"C/K 3500",
"550",
"328",
"Death Proof",
"750",
"P/U",
"944",
"(Cng) 2500",
"2500 Gas",
"C/K 1500",
"/Mercury Comet",
"924",
"2016",
"C/K 10",
"2013",
"Outlander +",
"544",
"325",
"428",
"Diesels Cummins",
"Camry Se(Sports",
"750I /",
"250",
"Cb",
"4Runner Limited,",
"525",
"C/V",
"/ Vmi",
"* Vmi",
"600",
"// Vmi",
"135",
"626",
"350Z -",
"2500 4",
"122",
"6500",
"997",
"1600",
"8500",
"128",
"968",
"3 6",
"928",
"7",
"228",
"/Vmi Conversion",
"Monza 2+2",
"3/4 Ton",
"1.5",
"460",
"2005",
"1954",
"7500",
"323",
"4S3Bmbg60A3217471",
"220S /",
"C/10",
"430",
"420",
"670",
"15",
"6000",
"4Runner Sr5/Sr5",
"760",
"C",
"30 Flatbed",
"3500 &",
"Marineer,Premier",
"3/4T 4Wd",
"M4 -",
"2500 Slt*",
"330",
"Tiguan *Awd",
'"T"',
"350 4×4",
"280",
" -@Benz E350",
"Trailblazer Lssuvw/",
"(S)Port (S)Edan",
"3500 Deisel",
"Accord -",
"Spark -",
"Malibu -",
"520",
"/ Accord",
"300-Hemi V8!!",
"510",
'T-150 130"',
"A4 **",
"A4 **Awd,",
"C/K 20",
"C/30",
"911/996 Carrera",
"-150 Xlt",
"29",
"500 Pop,",
"1500 $374",
"$362.47, $1000",
"F-150 Stx,Only",
"1500 $398.43,",
"1500 $381.17,",
"Xt5 $391",
"3500 Slt/Laramie",
"/ Durango",
"& Altima",
"/ Braun",
"86 **",
"C10/K10 K10",
"530Xi -",
"4.6",
"C/K 2500",
"960",
"C/T Hicube",
"540",
"50",
" -@ ",
"3 Select",
"- 328I","Remeo","Romeo", "Martin", "A" , "A4 **", "A4 ** Awd,",
"A3 2.0L","A6 2,7T", "4 Door", "Gsx &", "(210)", "(Cng) 2500", "1 1/2",
"1 Ton", "1-Ton", "4 wd" "(300)", "3", "1500 $374",
"2500 $488",
"Titan Sv,$392",
"$362.47, $1000",
"Titan Sv,$392",
"1500 $398.43,",
"Pacifica $293.25",
"Journey $299",
"Equinox $188.77Month,",
"1500 $398.43,",
"1500 $381.17,",
"Edge $270",
"Pacifica $293.25",
"Equinox $188.77Month,",
"Xt5 $391","One Ton",
"1/2 Ton",
"1 Ton",
"1.5 Ton",
"1-Ton Deluxe",
"3/4 Ton",
"1.5 Ton",
"1 Ton",
"1 Ton",
"1 Ton",
"1-Ton",
"3/4 Ton",
"1 Ton",
"Daytona Turbo",
"1/2 Ton",
"1 Ton",
"1 Ton",
"One Ton",
"One Ton",
"3/4 Ton",
"1/2 Ton",
"1/2 Ton",
"1 Ton",
"3/4 Ton",
"3/4 Ton",
"3/4 Ton",
"1/2 Ton",
"Kc 1/2Ton",
"3/4 Ton",
"Half Ton",
"/ Bertone",
"1/2 Ton",
"1 Ton"
]
def Bogus(x,y):
    for i in x:
        y = y[y.model_updated!=i]
        
Bogus(Values,Cars_df)
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 373157 entries, 27 to 426879
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   price          373157 non-null  float64
 1   year           373157 non-null  float64
 2   manufacturer   373157 non-null  object 
 3   model          373157 non-null  object 
 4   condition      373157 non-null  object 
 5   cylinders      221992 non-null  object 
 6   fuel           370990 non-null  object 
 7   odometer       370986 non-null  float64
 8   transmission   371470 non-null  object 
 9   drive          261229 non-null  object 
 10  type           294964 non-null  object 
 11  years_used     373157 non-null  float64
 12  model_updated  373157 non-null  object 
dtypes: float64(4), object(9)
memory usage: 39.9+ MB


In [38]:
Cars_df["model_updated"].nunique()

10950

In [39]:
Cars_df["model_updated"].head()

27       Sierra 1500
28    Silverado 1500
29    Silverado 1500
30     Tundra Double
31         F-150 Xlt
Name: model_updated, dtype: object

In [40]:
Cars_df["model_updated"].nunique()

10950

In [41]:
# checking how many models are there with null value
Cars_df["model"].loc[Cars_df["cylinders"].isnull()].nunique()

10026

In [42]:
# it is better to drop these null values instead of having them on the dataframe
Cars_df.dropna(subset=["cylinders"], inplace=True)
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 221992 entries, 27 to 426878
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   price          221992 non-null  float64
 1   year           221992 non-null  float64
 2   manufacturer   221992 non-null  object 
 3   model          221992 non-null  object 
 4   condition      221992 non-null  object 
 5   cylinders      221992 non-null  object 
 6   fuel           220876 non-null  object 
 7   odometer       220947 non-null  float64
 8   transmission   221818 non-null  object 
 9   drive          189302 non-null  object 
 10  type           198006 non-null  object 
 11  years_used     221992 non-null  float64
 12  model_updated  221992 non-null  object 
dtypes: float64(4), object(9)
memory usage: 23.7+ MB


In [43]:
#drop the null values in drive, type

Cars_df.dropna(subset=["drive", "type"], inplace=True)
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 171618 entries, 31 to 426878
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   price          171618 non-null  float64
 1   year           171618 non-null  float64
 2   manufacturer   171618 non-null  object 
 3   model          171618 non-null  object 
 4   condition      171618 non-null  object 
 5   cylinders      171618 non-null  object 
 6   fuel           170789 non-null  object 
 7   odometer       170715 non-null  float64
 8   transmission   171605 non-null  object 
 9   drive          171618 non-null  object 
 10  type           171618 non-null  object 
 11  years_used     171618 non-null  float64
 12  model_updated  171618 non-null  object 
dtypes: float64(4), object(9)
memory usage: 18.3+ MB


In [44]:
#drop the null values in fuel, odometer, title statue, transmission

Cars_df.dropna(subset=["fuel", "odometer"], inplace=True)

Cars_df=Cars_df.drop(["years_used"], axis=1)
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 169889 entries, 31 to 426878
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   price          169889 non-null  float64
 1   year           169889 non-null  float64
 2   manufacturer   169889 non-null  object 
 3   model          169889 non-null  object 
 4   condition      169889 non-null  object 
 5   cylinders      169889 non-null  object 
 6   fuel           169889 non-null  object 
 7   odometer       169889 non-null  float64
 8   transmission   169877 non-null  object 
 9   drive          169889 non-null  object 
 10  type           169889 non-null  object 
 11  model_updated  169889 non-null  object 
dtypes: float64(3), object(9)
memory usage: 16.8+ MB


In [45]:
Cars_df.describe()

price           year      odometer
count  1.698890e+05  169889.000000  1.698890e+05
mean   4.831827e+04    2010.619487  1.038042e+05
std    9.473803e+06       8.877157  1.641917e+05
min    1.000000e+00    1900.000000  0.000000e+00
25%    6.755000e+03    2007.000000  4.932900e+04
50%    1.300000e+04    2013.000000  9.673800e+04
75%    2.548600e+04    2016.000000  1.412000e+05
max    3.736929e+09    2022.000000  1.000000e+07

In [46]:
# checking the Min values in prices and replacing them with Avearage


# we are filtering all the outliers between min and max value
q_low= Cars_df["price"].quantile(0.01)
q_hi= Cars_df["price"].quantile(0.99)

Cars_df = Cars_df[(Cars_df["price"]<q_hi) & (Cars_df["price"]>q_low)]

In [47]:
Cars_df.describe()

price           year      odometer
count  166476.000000  166476.000000  1.664760e+05
mean    16912.539315    2010.573806  1.045745e+05
std     12717.817295       8.803599  1.619695e+05
min       175.000000    1900.000000  0.000000e+00
25%      6900.000000    2007.000000  5.042750e+04
50%     13000.000000    2013.000000  9.769350e+04
75%     24995.000000    2016.000000  1.420000e+05
max     63990.000000    2022.000000  1.000000e+07

In [48]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 166476 entries, 31 to 426878
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   price          166476 non-null  float64
 1   year           166476 non-null  float64
 2   manufacturer   166476 non-null  object 
 3   model          166476 non-null  object 
 4   condition      166476 non-null  object 
 5   cylinders      166476 non-null  object 
 6   fuel           166476 non-null  object 
 7   odometer       166476 non-null  float64
 8   transmission   166464 non-null  object 
 9   drive          166476 non-null  object 
 10  type           166476 non-null  object 
 11  model_updated  166476 non-null  object 
dtypes: float64(3), object(9)
memory usage: 16.5+ MB


In [49]:
Cars_df["year"]=Cars_df["year"].astype(int)
Cars_df.rename(columns = {'odometer':'Distance_Traveled'}, inplace = True)

In [50]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 166476 entries, 31 to 426878
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   price              166476 non-null  float64
 1   year               166476 non-null  int32  
 2   manufacturer       166476 non-null  object 
 3   model              166476 non-null  object 
 4   condition          166476 non-null  object 
 5   cylinders          166476 non-null  object 
 6   fuel               166476 non-null  object 
 7   Distance_Traveled  166476 non-null  float64
 8   transmission       166464 non-null  object 
 9   drive              166476 non-null  object 
 10  type               166476 non-null  object 
 11  model_updated      166476 non-null  object 
dtypes: float64(2), int32(1), object(9)
memory usage: 15.9+ MB


In [51]:
csv_data = Cars_df.to_csv("Model.csv",columns=["manufacturer",'model_updated', 'model'])

In [52]:
# droping model
Cars_df=Cars_df.drop('model', axis=1)

In [53]:
Cars_df["model_updated"] = Cars_df["manufacturer"] + " " + Cars_df["model_updated"]

In [54]:
Cars_df["model_updated"].head()

31                 Ford F-150 Xlt
32                Gmc Sierra 2500
33       Chevrolet Silverado 1500
34                  Toyota Tacoma
35    Chevrolet Colorado Extended
Name: model_updated, dtype: object

In [55]:
Cars_df.dropna(subset=["transmission"], inplace=True)

In [56]:
# Backup Cleaned Copy
Backup_Cleaned=Cars_df.copy()


In [57]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 166464 entries, 31 to 426878
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   price              166464 non-null  float64
 1   year               166464 non-null  int32  
 2   manufacturer       166464 non-null  object 
 3   condition          166464 non-null  object 
 4   cylinders          166464 non-null  object 
 5   fuel               166464 non-null  object 
 6   Distance_Traveled  166464 non-null  float64
 7   transmission       166464 non-null  object 
 8   drive              166464 non-null  object 
 9   type               166464 non-null  object 
 10  model_updated      166464 non-null  object 
dtypes: float64(2), int32(1), object(8)
memory usage: 14.6+ MB


In [58]:
Cars_df=Cars_df[["price","year", "manufacturer", "model_updated", "condition", 
        "cylinders", "fuel", "transmission", "drive", "type"]]

In [59]:
Cars_df.to_csv("cleaned_Car.csv")

In [60]:
Cars_df.to_csv("D:/Studies/My Projects/Data Science/Car Prediction/WebDeployment/cleaned_Car.csv")

In [61]:
Cars_df["model_updated"].nunique()

8045

### Creating a linear Regression Model

In [62]:
# breaking the Dependent variable & Independent Variable
x = Cars_df.drop(columns="price")
y = Cars_df["price"]

In [63]:
x.head()

year manufacturer                model_updated  condition    cylinders  \
31  2013         Ford               Ford F-150 Xlt  Excellent  6 cylinders   
32  2012          Gmc              Gmc Sierra 2500       Good  8 cylinders   
33  2016    Chevrolet     Chevrolet Silverado 1500       Good  6 cylinders   
34  2019       Toyota                Toyota Tacoma  Excellent  6 cylinders   
35  2016    Chevrolet  Chevrolet Colorado Extended       Good  6 cylinders   

   fuel transmission drive    type  
31  Gas    Automatic   Rwd   Truck  
32  Gas        Other   4Wd  Pickup  
33  Gas        Other   4Wd  Pickup  
34  Gas    Automatic   4Wd   Truck  
35  Gas        Other   4Wd  Pickup

In [64]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [65]:
# importing modules for linear regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [66]:
import sklearn
print('sklearn: {}'. format(sklearn. __version__)) 

sklearn: 1.1.1


In [67]:
ohe = OneHotEncoder()
ohe.fit(x[["manufacturer", "condition", "cylinders", "fuel", 
           "transmission", "drive" , "type","model_updated"]])

OneHotEncoder()

In [68]:
Cars_df.dtypes

price            float64
year               int32
manufacturer      object
model_updated     object
condition         object
cylinders         object
fuel              object
transmission      object
drive             object
type              object
dtype: object

In [69]:
ohe.categories_

[array(['Acura', 'Alfa-Romeo', 'Aston-Martin', 'Audi', 'Bmw', 'Buick',
        'Cadillac', 'Chevrolet', 'Chrysler', 'Datsun', 'Dodge', 'Ferrari',
        'Fiat', 'Ford', 'Gmc', 'Harley-Davidson', 'Honda', 'Hyundai',
        'Infiniti', 'Jaguar', 'Jeep', 'Kia', 'Land Rover', 'Lexus',
        'Lincoln', 'Mazda', 'Mercedes-Benz', 'Mercury', 'Mini',
        'Mitsubishi', 'Nissan', 'Pontiac', 'Porsche', 'Ram', 'Rover',
        'Saturn', 'Subaru', 'Tesla', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Excellent', 'Fair', 'Good', 'Like New', 'New', 'Salvage'],
       dtype=object),
 array(['10 cylinders', '12 cylinders', '3 cylinders', '4 cylinders',
        '5 cylinders', '6 cylinders', '8 cylinders', 'other'], dtype=object),
 array(['Diesel', 'Electric', 'Gas', 'Hybrid', 'Other'], dtype=object),
 array(['Automatic', 'Manual', 'Other'], dtype=object),
 array(['4Wd', 'Fwd', 'Rwd'], dtype=object),
 array(['Bus', 'Convertible', 'Coupe', 'Hatchback', 'Mini-Van', 'Offroad',
   

In [70]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),
                                       ["manufacturer", "condition", "cylinders", "fuel", 
           "transmission", "drive" , "type","model_updated"]), remainder="passthrough")

In [71]:
lr=LinearRegression()

In [72]:
pipe=make_pipeline(column_trans,lr)

In [73]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Acura', 'Alfa-Romeo', 'Aston-Martin', 'Audi', 'Bmw', 'Buick',
       'Cadillac', 'Chevrolet', 'Chrysler', 'Datsun', 'Dodge', 'Ferrari',
       'Fiat', 'Ford', 'Gmc', 'Harley-Davidson', 'Honda', 'Hyundai',
       'Infiniti', 'Jaguar', 'Jeep', 'Kia',...
                                                                            array(['Bus', 'Convertible', 'Coupe', 'Hatchback', 'Mini-Van', 'Offroad',
       'Other', 'Pickup', 'Sedan', 'Suv', 'Truck', 'Van', 'Wagon'],
      dtype=object),
                                                                            array(['Acura 2002 Rsx', 'Acura 3.0Cl', 'Acura 3.2 Cl', ...,
       'Volvo Xc90 T6', 'Volvo Xc90 T8', 'Volvo Xc90 V8'], dtype=object)]),
                                                  ['manufacturer', 'condition',
                                                   'cylinders', 'fuel',
                                                   'transmission', 'drive',
                                                   'type',
                                                   'model_updated'])])),
                ('linearregression', LinearRegression())])

In [74]:
y_pred=pipe.predict(x_test)

In [75]:
y_pred

array([ 1929.47844757, 40016.23105435, 35566.68107264, ...,
       26874.67734781,  5655.35947479, 33086.35843735])

In [76]:
# checking for r2 socre
r2_score(y_test, y_pred)

0.6099570296583919

In [77]:
# checking for maximum possible r2 scores
scores = []
for i in range(100):
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train, y_train)
    y_pred=pipe.predict(x_test)
    print(i, r2_score(y_test, y_pred))
    scores.append(r2_score(y_test, y_pred))

0 0.616331455975915
1 0.6339102676445632
2 0.6247209508353293
3 0.6396498858370699
4 0.6288588486740689
5 0.6233024771306473
6 0.6297006230116027
7 0.6387761705431845
8 0.6296276961696071
9 0.6332590294211027
10 0.6324840906841125
11 0.6284749292849464
12 0.6267223484157216
13 0.6226054847815774
14 0.6300521385513794
15 0.6427139518981047
16 0.6349361054932946
17 0.6311337177093757
18 0.6224667805002144
19 0.6366521797643651
20 0.6401450508614448
21 0.6327486001990021
22 0.629478219603371
23 0.6279094715102485
24 0.6217847046703624
25 0.6364024157791199
26 0.6199849705380842
27 0.6304362613932366
28 0.6284720847503955
29 0.6324296734673267
30 0.6124272559043575
31 0.6213200713774127
32 0.629460986263116
33 0.6312917636630735
34 0.6263652707360584
35 0.6301769047804021
36 0.6209475851208581
37 0.6216204365670208
38 0.6208786240468002
39 0.6229446155855077
40 0.6344094409229548
41 0.6341651143632149
42 0.6331708583256301
43 0.6217971146945278
44 0.6182101669609725
45 0.6121096380552833
4

In [78]:
np.argmax(scores)

15

In [79]:
scores[np.argmax(scores)]

0.6427139518981047

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(x_train, y_train)
y_pred=pipe.predict(x_test)
r2_score(y_test, y_pred)

0.6427139518981047

In [81]:
import pickle

In [82]:
pickle.dump(pipe,open("LinearRegressionModel.pkl", "wb"))
pickle.dump(pipe,open("WebDeployment/LinearRegressionModel.pkl", "wb"))

In [83]:
pipe.predict(pd.DataFrame([["2000", "Ford", "Good", 
                            "6 cylinders", "Diesel", 90000, "Automatic",
                            "Fwd", "Suv", "Ford F-150"]], 
                          columns=["year","manufacturer","condition",
                                   "cylinders","fuel","Distance_Traveled",
                                   "transmission","drive", "type", "model_updated",]))

array([13331.06614585])

In [84]:
from sklearn import metrics
test_y, linear_predicted_rating = [1,2,3,4], [1,2,3,5]
metrics.accuracy_score(test_y, linear_predicted_rating)

0.75