In [1]:
# import Python packages
import pandas as pd
import numpy as np
import matplotlib as mlp
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
# Loading the dataset
Cars_df=pd.read_csv("D:/Studies/My Projects/Data Science/Car Prediction/Data/vehicles.csv")
Cars_df.head()

id                                                url  \
0  7222695916  https://prescott.craigslist.org/cto/d/prescott...   
1  7218891961  https://fayar.craigslist.org/ctd/d/bentonville...   
2  7221797935  https://keys.craigslist.org/cto/d/summerland-k...   
3  7222270760  https://worcester.craigslist.org/cto/d/west-br...   
4  7210384030  https://greensboro.craigslist.org/cto/d/trinit...   

                   region                         region_url  price  year  \
0                prescott    https://prescott.craigslist.org   6000   NaN   
1            fayetteville       https://fayar.craigslist.org  11900   NaN   
2            florida keys        https://keys.craigslist.org  21000   NaN   
3  worcester / central MA   https://worcester.craigslist.org   1500   NaN   
4              greensboro  https://greensboro.craigslist.org   4900   NaN   

  manufacturer model condition cylinders  ... size  type paint_color  \
0          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
1          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
2          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
3          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
4          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   

  image_url description county state lat long posting_date  
0       NaN         NaN    NaN    az NaN  NaN          NaN  
1       NaN         NaN    NaN    ar NaN  NaN          NaN  
2       NaN         NaN    NaN    fl NaN  NaN          NaN  
3       NaN         NaN    NaN    ma NaN  NaN          NaN  
4       NaN         NaN    NaN    nc NaN  NaN          NaN  

[5 rows x 26 columns]

In [3]:
# checking for no rows, columns
print("This Dataset {} Rows and {} columns".format(Cars_df.shape[0],Cars_df.shape[1]))

This Dataset 426880 Rows and 26 columns


In [4]:
# printing the full summary of dataset
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            426880 non-null  int64  
 1   url           426880 non-null  object 
 2   region        426880 non-null  object 
 3   region_url    426880 non-null  object 
 4   price         426880 non-null  int64  
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  object 
 7   model         421603 non-null  object 
 8   condition     252776 non-null  object 
 9   cylinders     249202 non-null  object 
 10  fuel          423867 non-null  object 
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  object 
 13  transmission  424324 non-null  object 
 14  VIN           265838 non-null  object 
 15  drive         296313 non-null  object 
 16  size          120519 non-null  object 
 17  type          334022 non-null  object 
 18  pain

In [5]:
# checking the no of unique values for manufacturer
Cars_df['manufacturer'].unique()

array([nan, 'gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa-romeo',
       'subaru', 'acura', 'hyundai', 'mercedes-benz', 'bmw', 'mitsubishi',
       'volkswagen', 'porsche', 'kia', 'rover', 'ferrari', 'mini',
       'pontiac', 'fiat', 'tesla', 'saturn', 'mercury', 'harley-davidson',
       'datsun', 'aston-martin', 'land rover', 'morgan'], dtype=object)

In [6]:
# Checking for Unique Values
Cars_df["model"].unique()

array([nan, 'sierra 1500 crew cab slt', 'silverado 1500', ...,
       'gand wagoneer', '96 Suburban', 'Paige Glenbrook Touring'],
      dtype=object)

In [7]:
# Checking for count of Unique Values
Cars_df["model"].nunique()

29667

In [8]:
# Checking for Unique Values for conditions
Cars_df["condition"].unique()

array([nan, 'good', 'excellent', 'fair', 'like new', 'new', 'salvage'],
      dtype=object)

In [9]:
# Checking for Unique Values for cylinders
Cars_df["cylinders"].unique()

array([nan, '8 cylinders', '6 cylinders', '4 cylinders', '5 cylinders',
       'other', '3 cylinders', '10 cylinders', '12 cylinders'],
      dtype=object)

In [10]:
# checking for Unique values for fuel
Cars_df["fuel"].unique()

array([nan, 'gas', 'other', 'diesel', 'hybrid', 'electric'], dtype=object)

In [11]:
# checking for unique values for odometer
Cars_df["odometer"].unique()

array([    nan,  57923.,  71229., ..., 172511.,  94964.,  26892.])

In [12]:
# checking for unique values for title_status  
Cars_df["title_status"].unique()

array([nan, 'clean', 'rebuilt', 'lien', 'salvage', 'missing',
       'parts only'], dtype=object)

In [13]:
# checking for unique values for drive
Cars_df["VIN"].unique()

array([nan, '3GTP1VEC4EG551563', '1GCSCSE06AZ123805', ...,
       '2HGES15535H620534', '1FDWF37P64EA24868', 'SAJGX2749VCOO8376'],
      dtype=object)

In [14]:
# checking for unique values for drive
Cars_df["drive"].unique()

array([nan, 'rwd', '4wd', 'fwd'], dtype=object)

In [15]:
# checking for unique values for size.
Cars_df["size"].unique()

array([nan, 'full-size', 'mid-size', 'compact', 'sub-compact'],
      dtype=object)

In [16]:
# checking for unique values for type.
Cars_df["type"].unique()
#Cars_df["type"].isnull().sum()

array([nan, 'pickup', 'truck', 'other', 'coupe', 'SUV', 'hatchback',
       'mini-van', 'sedan', 'offroad', 'bus', 'van', 'convertible',
       'wagon'], dtype=object)

In [17]:
# checking for unique values for paint_color   .
Cars_df["paint_color"].unique()

array([nan, 'white', 'blue', 'red', 'black', 'silver', 'grey', 'brown',
       'yellow', 'orange', 'green', 'custom', 'purple'], dtype=object)

## Cleaning Dataset based on features

Here are the notes for cleaning which shoule be considered when cleaning.
- on the Manufacturer column we can see NAN Values. (Dropping those Values since there is no ways getting those values)
- on the  value for price drop if it is 0 (first replace with NP.nan and remove those values)
- on the Model Column we can see NAN Values Dropping those Values since there is no ways getting those values)
- There are almost 30000 unique values,so we have to find a way reduce those no of unique values as first stage we will trt split the Model into core model by considering first two words.
- Np.Nan can be adjusted based on number of years if the car is 0-2 "excellent" 3-6 to "fair", 7-12 to "Good" & more than 12 "salvage"
- "Vintage" car condition is if they manufactured year in between 1919 to 1930.
- "Antique" car condition is if they manufactured year in between 1975 or earlier upto 1930.
- "Classic" car condition is if they are Manufactred year is 2000 or earlier upto 1975.
- remove the np.nan values in cylinder, other.
- remove the "np.nan" values in fuel remove other.
- remove the "np.nan" in odometer
- remove the "np.nan" in Title status
- Drop the VIN number form dataframe (Reason for droping will not help for prediction since all the VIN Values are unique for each cars "17-digit code of letters and numbers that identifies a car uniquely and is assigned at the time a vehicle is manufactured")
- Remove the "np.nan" values for drive.
- Drop the size column.
- Remove the "np.nan" values for type.
- replace the "np.nan" values with maximum.
- drop image url drop description columns from dataframe.
- drop county column since there is no value on that.
- for state Column replace the short name with full name.
- drop lat long columns (we can use to create map with folium based on position)
- Posting date should can be used for creating line chart for understanding when they are selling more cars. drop them after that

After cleaning we can expect arround 200 to 250k of cleaned data points for EDA.

In [18]:
# Getting a backup of dataframe before data manipulation
Backup=Cars_df.copy()

In [19]:
# Checking for total no of null values in full dataset
Cars_df.isnull().sum()

id                   0
url                  0
region               0
region_url           0
price                0
year              1205
manufacturer     17646
model             5277
condition       174104
cylinders       177678
fuel              3013
odometer          4400
title_status      8242
transmission      2556
VIN             161042
drive           130567
size            306361
type             92858
paint_color     130203
image_url           68
description         70
county          426880
state                0
lat               6549
long              6549
posting_date        68
dtype: int64

### Dropping columns from DataFrame

We are dropping following features from the dataframe & Reasons

 - For First Round we are going to cleanout following columns
     - VIN Column - VIN is a unique key number given for each car by manufacturer, so it cannot be used as a feature for prediction.
     - url for link ad 
     - Region_url
     - Droping model
     - County column - This column is fully empty so we should remove those
     - size column - This column has 75% of values null.
     - Description - Not required
     - lat - not Required
     - Long - not Required
     - Image Url - Not required
     

In [20]:
# to remove columns df.drop(["XXX"],axis=1)
Cars_df=Cars_df.drop(["url", "region_url","VIN", "county", "size", "description","lat", "long", 
                      "image_url", "paint_color","posting_date", "region", ], axis=1)


Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            426880 non-null  int64  
 1   region        426880 non-null  object 
 2   price         426880 non-null  int64  
 3   year          425675 non-null  float64
 4   manufacturer  409234 non-null  object 
 5   model         421603 non-null  object 
 6   condition     252776 non-null  object 
 7   cylinders     249202 non-null  object 
 8   fuel          423867 non-null  object 
 9   odometer      422480 non-null  float64
 10  title_status  418638 non-null  object 
 11  transmission  424324 non-null  object 
 12  drive         296313 non-null  object 
 13  type          334022 non-null  object 
 14  state         426880 non-null  object 
 15  posting_date  426812 non-null  object 
dtypes: float64(2), int64(2), object(12)
memory usage: 52.1+ MB


In [21]:
#checking for possible dropout values 
Cars_df.isnull().any(axis=1).sum()

299648

### Removing np.nan values from dataframe.

In [22]:
# Price
# replacing the zero value to Np.nan, because the if the price is zero it means it is free for sales.
Cars_df["price"].replace(0,np.nan, inplace=True)
Cars_df["price"].isnull().sum()

32895

In [23]:
# Dropping the null value from prices
Cars_df.dropna(subset=["price"], inplace=True)

In [24]:
Cars_df["price"].isnull().sum()

0

In [25]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 393985 entries, 0 to 426879
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            393985 non-null  int64  
 1   region        393985 non-null  object 
 2   price         393985 non-null  float64
 3   year          392812 non-null  float64
 4   manufacturer  377800 non-null  object 
 5   model         389284 non-null  object 
 6   condition     242596 non-null  object 
 7   cylinders     233575 non-null  object 
 8   fuel          391391 non-null  object 
 9   odometer      391695 non-null  float64
 10  title_status  386251 non-null  object 
 11  transmission  392162 non-null  object 
 12  drive         273731 non-null  object 
 13  type          308053 non-null  object 
 14  state         393985 non-null  object 
 15  posting_date  393923 non-null  object 
dtypes: float64(3), int64(1), object(12)
memory usage: 51.1+ MB


In [26]:
# dropping null values form Year
Cars_df.dropna(subset=["year"], inplace=True)

In [27]:
# dropping null values form manufacturer
Cars_df.dropna(subset=["manufacturer"], inplace=True)
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 377796 entries, 27 to 426879
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            377796 non-null  int64  
 1   region        377796 non-null  object 
 2   price         377796 non-null  float64
 3   year          377796 non-null  float64
 4   manufacturer  377796 non-null  object 
 5   model         373157 non-null  object 
 6   condition     232120 non-null  object 
 7   cylinders     224296 non-null  object 
 8   fuel          375629 non-null  object 
 9   odometer      375619 non-null  float64
 10  title_status  370522 non-null  object 
 11  transmission  376093 non-null  object 
 12  drive         263870 non-null  object 
 13  type          297464 non-null  object 
 14  state         377796 non-null  object 
 15  posting_date  377796 non-null  object 
dtypes: float64(3), int64(1), object(12)
memory usage: 49.0+ MB


In [28]:
# Replacing conditions null value with following Criteria
# Np.Nan can be adjusted based on number of years if the car is 
#0-2 "excellent" 3-6 to "Good", 7-12 to "fair" & more than 12 "salvage"

Cars_df["years_used"]=2022-Cars_df["year"]
Cars_df["years_used"].head()
Cars_df["years_used"].astype(int)

27         8
28        12
29         2
30         5
31         9
          ..
426875     3
426876     2
426877     2
426878     4
426879     3
Name: years_used, Length: 377796, dtype: int32

In [29]:
# changing null value in condition to years used.

m1 = (Cars_df["condition"].isnull()) & (Cars_df["years_used"]<=2)
m2 = (Cars_df["condition"].isnull()) & (Cars_df["years_used"]>=3) & (Cars_df["years_used"]<=6)
m3 = (Cars_df["condition"].isnull()) & (Cars_df["years_used"]>=7) & (Cars_df["years_used"]<=12)
m4 = (Cars_df["condition"].isnull()) & (Cars_df["years_used"]>12)


Cars_df.loc[m1, "condition"]="excellent"
Cars_df.loc[m2, "condition"]="good"
Cars_df.loc[m3, "condition"]="fair"
Cars_df.loc[m4, "condition"]="salvage"

In [30]:
Cars_df["condition"].unique()

array(['good', 'excellent', 'fair', 'salvage', 'like new', 'new'],
      dtype=object)

In [31]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 377796 entries, 27 to 426879
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            377796 non-null  int64  
 1   region        377796 non-null  object 
 2   price         377796 non-null  float64
 3   year          377796 non-null  float64
 4   manufacturer  377796 non-null  object 
 5   model         373157 non-null  object 
 6   condition     377796 non-null  object 
 7   cylinders     224296 non-null  object 
 8   fuel          375629 non-null  object 
 9   odometer      375619 non-null  float64
 10  title_status  370522 non-null  object 
 11  transmission  376093 non-null  object 
 12  drive         263870 non-null  object 
 13  type          297464 non-null  object 
 14  state         377796 non-null  object 
 15  posting_date  377796 non-null  object 
 16  years_used    377796 non-null  float64
dtypes: float64(4), int64(1), object(12)
memory usag

In [32]:
# Droping the null values in models
Cars_df.dropna(subset=["model"], inplace=True)

In [33]:
Cars_df["model"].head()

27    sierra 1500 crew cab slt
28              silverado 1500
29         silverado 1500 crew
30        tundra double cab sr
31                   f-150 xlt
Name: model, dtype: object

In [34]:
# split the model name and get the first two out of those.
Cars_df["model"]=Cars_df["model"].str.split(" ").str.slice(0,1).str.join(" ")
Cars_df["model"].head()

27       sierra
28    silverado
29    silverado
30       tundra
31        f-150
Name: model, dtype: object

In [35]:
Cars_df["model"].nunique()

2991

In [36]:
Cars_df["model"].head()

27       sierra
28    silverado
29    silverado
30       tundra
31        f-150
Name: model, dtype: object

In [37]:
Cars_df["model"].nunique()

2991

In [38]:
Cars_df["manufacturer"]=Cars_df["manufacturer"].str.capitalize()
Cars_df["model"]=Cars_df["model"].str.capitalize()

In [39]:
# checking how many models are there with null value
Cars_df["model"].loc[Cars_df["cylinders"].isnull()].nunique()

1706

In [40]:
# it is better to drop these null values instead of having them on the dataframe
Cars_df.dropna(subset=["cylinders"], inplace=True)
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 221992 entries, 27 to 426878
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            221992 non-null  int64  
 1   region        221992 non-null  object 
 2   price         221992 non-null  float64
 3   year          221992 non-null  float64
 4   manufacturer  221992 non-null  object 
 5   model         221992 non-null  object 
 6   condition     221992 non-null  object 
 7   cylinders     221992 non-null  object 
 8   fuel          220876 non-null  object 
 9   odometer      220947 non-null  float64
 10  title_status  215955 non-null  object 
 11  transmission  221818 non-null  object 
 12  drive         189302 non-null  object 
 13  type          198006 non-null  object 
 14  state         221992 non-null  object 
 15  posting_date  221992 non-null  object 
 16  years_used    221992 non-null  float64
dtypes: float64(4), int64(1), object(12)
memory usag

In [41]:
Cars_df["years_used"].loc[Cars_df["condition"].isnull()].unique()

array([], dtype=float64)

In [42]:
#drop the null values in drive, type

Cars_df.dropna(subset=["drive", "type"], inplace=True)
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 171618 entries, 31 to 426878
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            171618 non-null  int64  
 1   region        171618 non-null  object 
 2   price         171618 non-null  float64
 3   year          171618 non-null  float64
 4   manufacturer  171618 non-null  object 
 5   model         171618 non-null  object 
 6   condition     171618 non-null  object 
 7   cylinders     171618 non-null  object 
 8   fuel          170789 non-null  object 
 9   odometer      170715 non-null  float64
 10  title_status  169000 non-null  object 
 11  transmission  171605 non-null  object 
 12  drive         171618 non-null  object 
 13  type          171618 non-null  object 
 14  state         171618 non-null  object 
 15  posting_date  171618 non-null  object 
 16  years_used    171618 non-null  float64
dtypes: float64(4), int64(1), object(12)
memory usag

In [43]:
#drop the null values in fuel, odometer, title statue, transmission

Cars_df.dropna(subset=["fuel", "odometer", "title_status", "transmission"], inplace=True)

Cars_df=Cars_df.drop(["years_used"], axis=1)
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 167307 entries, 31 to 426878
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            167307 non-null  int64  
 1   price         167307 non-null  float64
 2   year          167307 non-null  float64
 3   manufacturer  167307 non-null  object 
 4   model         167307 non-null  object 
 5   condition     167307 non-null  object 
 6   cylinders     167307 non-null  object 
 7   fuel          167307 non-null  object 
 8   odometer      167307 non-null  float64
 9   title_status  167307 non-null  object 
 10  transmission  167307 non-null  object 
 11  drive         167307 non-null  object 
 12  type          167307 non-null  object 
 13  state         167307 non-null  object 
dtypes: float64(3), int64(1), object(10)
memory usage: 19.1+ MB


In [44]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 167307 entries, 31 to 426878
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            167307 non-null  int64  
 1   price         167307 non-null  float64
 2   year          167307 non-null  float64
 3   manufacturer  167307 non-null  object 
 4   model         167307 non-null  object 
 5   condition     167307 non-null  object 
 6   cylinders     167307 non-null  object 
 7   fuel          167307 non-null  object 
 8   odometer      167307 non-null  float64
 9   title_status  167307 non-null  object 
 10  transmission  167307 non-null  object 
 11  drive         167307 non-null  object 
 12  type          167307 non-null  object 
 13  state         167307 non-null  object 
dtypes: float64(3), int64(1), object(10)
memory usage: 19.1+ MB


In [45]:
Cars_df.describe()

id         price           year      odometer
count  1.673070e+05  1.673070e+05  167307.000000  1.673070e+05
mean   7.311683e+09  4.885267e+04    2010.571076  1.040515e+05
std    4.280037e+06  9.546626e+06       8.913687  1.652651e+05
min    7.301584e+09  1.000000e+00    1900.000000  0.000000e+00
25%    7.308418e+09  6.800000e+03    2007.000000  4.948100e+04
50%    7.312870e+09  1.324900e+04    2013.000000  9.700000e+04
75%    7.315276e+09  2.559000e+04    2016.000000  1.414290e+05
max    7.317101e+09  3.736929e+09    2022.000000  1.000000e+07

In [46]:
# checking the Min values in prices and replacing them with Avearage


# we are filtering all the outliers between min and max value
q_low= Cars_df["price"].quantile(0.01)
q_hi= Cars_df["price"].quantile(0.99)

Cars_df = Cars_df[(Cars_df["price"]<q_hi) & (Cars_df["price"]>q_low)]

In [47]:
Cars_df.describe()

id          price           year      odometer
count  1.639180e+05  163918.000000  163918.000000  1.639180e+05
mean   7.311682e+09   16969.155261    2010.523005  1.048525e+05
std    4.281362e+06   12714.245928       8.839590  1.630330e+05
min    7.301584e+09     176.000000    1900.000000  0.000000e+00
25%    7.308413e+09    6900.000000    2007.000000  5.073600e+04
50%    7.312872e+09   13249.500000    2013.000000  9.799500e+04
75%    7.315277e+09   24999.000000    2016.000000  1.421130e+05
max    7.317101e+09   63990.000000    2022.000000  1.000000e+07

In [48]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 163918 entries, 31 to 426878
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            163918 non-null  int64  
 1   price         163918 non-null  float64
 2   year          163918 non-null  float64
 3   manufacturer  163918 non-null  object 
 4   model         163918 non-null  object 
 5   condition     163918 non-null  object 
 6   cylinders     163918 non-null  object 
 7   fuel          163918 non-null  object 
 8   odometer      163918 non-null  float64
 9   title_status  163918 non-null  object 
 10  transmission  163918 non-null  object 
 11  drive         163918 non-null  object 
 12  type          163918 non-null  object 
 13  state         163918 non-null  object 
dtypes: float64(3), int64(1), object(10)
memory usage: 18.8+ MB


In [49]:
Cars_df["year"]=Cars_df["year"].astype(int)
Cars_df.rename(columns = {'odometer':'Distance_Traveled'}, inplace = True)


In [50]:
Cars_df=Cars_df.drop(["id"], axis=1)

In [51]:
Cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 163918 entries, 31 to 426878
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   price              163918 non-null  float64
 1   year               163918 non-null  int32  
 2   manufacturer       163918 non-null  object 
 3   model              163918 non-null  object 
 4   condition          163918 non-null  object 
 5   cylinders          163918 non-null  object 
 6   fuel               163918 non-null  object 
 7   Distance_Traveled  163918 non-null  float64
 8   title_status       163918 non-null  object 
 9   transmission       163918 non-null  object 
 10  drive              163918 non-null  object 
 11  type               163918 non-null  object 
 12  state              163918 non-null  object 
dtypes: float64(2), int32(1), object(10)
memory usage: 16.9+ MB


In [52]:
Values=["- 328i", "- benz", "- santa", '"t"', 
        "$362.47, $1000", "& altima", "(210)", 
        "(300)", "(cng) 2500", "(s)port (s)edan", 
        "/ accord", "/ braun", "/ durango", "/ vmi", 
        "// vmi", "/mercury comet", "/vmi conversion", 
        "♿", "♿ vmi", "1 1/2", "1 series", "1 ton", 
        "1.8t convertible", "1/2 ton", "100", "100 cs", 
        "100 fleet", "100 pick-up", "150", "1500", "1500 big", 
        "1500 lifted", "2 dr", "200", "2002", "210", "2500", 
        "2500 gas", "2500 hd", "2500 power", "3", "300", "300c", 
        "3500", "4500", "5", "500", "5500", "7 litre", "911",
        "C3500hd 6.5", "Ct 200h", "P", "Rc", "Two door", "Vmi ♿", "Yj"]

Cars_df=Cars_df[Cars_df.model.isin(Values)==False]


In [53]:
Cars_df["model"] = Cars_df["manufacturer"] + " " + Cars_df["model"]

In [54]:
# Backup Cleaned Copy
Backup_Cleaned=Cars_df.copy()

In [55]:
Cars_df.to_csv("cleaned_Car.csv")

In [56]:
Cars_df.to_csv("D:/Studies/My Projects/Data Science/Car Prediction/WebDeployment/cleaned_Car.csv")

In [57]:
States={'al':'Alabama',
'ak':'Alaska',
'az':'Arizona',
'ar':'Arkansas',
'ca':'California',
'co':'Colorado',
'ct':'Connecticut',
'de':'Delaware',
'fl':'Florida',
'ga':'Georgia',
'hi':'Hawaii',
'id':'Idaho',
'il':'Illinois',
'in':'Indiana',
'ia':'Iowa',
'ks':'Kansas',
'ky':'Kentucky',
'la':'Louisiana',
'me':'Maine',
'md':'Maryland',
'ma':'Massachusetts',
'mi':'Michigan',
'mn':'Minnesota',
'ms':'Mississippi',
'mo':'Missouri',
'mt':'Montana',
'ne':'Nebraska',
'nv':'Nevada',
'nh':'New Hampshire',
'nj':'New Jersey',
'nm':'New Mexico',
'ny':'New York',
'nc':'North Carolina',
'nd':'North Dakota',
'oh':'Ohio',
'ok':'Oklahoma',
'or':'Oregon',
'pa':'Pennsylvania',
'ri':'Rhode Island',
'sc':'South Carolina',
'sd':'South Dakota',
'tn':'Tennessee',
'tx':'Texas',
'ut':'Utah',
'vt':'Vermont',
'va':'Virginia',
'wa':'Washington',
'wv':'West Virginia',
'wi':'Wisconsin',
'wy':'Wyoming',
'dc':'Washington'}

Cars_df["state"].replace(States.keys(),States.values(),inplace=True)

In [75]:
Cars_df["model"].to_csv("Model.csv")

In [58]:
Cars_df["model"].to_csv("Model.csv")

In [59]:
Cars_df["model"].to_csv("Model.csv")

In [60]:
Cars_df["model"].nunique()

2540

### Creating a linear Regression Model

In [61]:
# breaking the Dependent variable & Independent Variable
x = Cars_df.drop(columns="price")
y = Cars_df["price"]

In [62]:
x.head()

year manufacturer                model  condition    cylinders fuel  \
31  2013         Ford           Ford F-150  excellent  6 cylinders  gas   
32  2012          Gmc           Gmc Sierra       good  8 cylinders  gas   
33  2016    Chevrolet  Chevrolet Silverado       good  6 cylinders  gas   
34  2019       Toyota        Toyota Tacoma  excellent  6 cylinders  gas   
35  2016    Chevrolet   Chevrolet Colorado       good  6 cylinders  gas   

    Distance_Traveled title_status transmission drive    type    state  
31           128000.0        clean    automatic   rwd   truck  Alabama  
32            68696.0        clean        other   4wd  pickup  Alabama  
33            29499.0        clean        other   4wd  pickup  Alabama  
34            43000.0        clean    automatic   4wd   truck  Alabama  
35            17302.0        clean        other   4wd  pickup  Alabama

In [63]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [64]:
# importing modules for linear regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [65]:
ohe = OneHotEncoder()
ohe.fit(x[["manufacturer", "condition", "cylinders", "fuel","title_status", 
           "transmission", "drive" , "type","model", "state"]])

OneHotEncoder()

In [66]:
Cars_df.dtypes

price                float64
year                   int32
manufacturer          object
model                 object
condition             object
cylinders             object
fuel                  object
Distance_Traveled    float64
title_status          object
transmission          object
drive                 object
type                  object
state                 object
dtype: object

In [67]:
ohe.categories_

[array(['Acura', 'Alfa-romeo', 'Aston-martin', 'Audi', 'Bmw', 'Buick',
        'Cadillac', 'Chevrolet', 'Chrysler', 'Datsun', 'Dodge', 'Ferrari',
        'Fiat', 'Ford', 'Gmc', 'Harley-davidson', 'Honda', 'Hyundai',
        'Infiniti', 'Jaguar', 'Jeep', 'Kia', 'Land rover', 'Lexus',
        'Lincoln', 'Mazda', 'Mercedes-benz', 'Mercury', 'Mini',
        'Mitsubishi', 'Nissan', 'Pontiac', 'Porsche', 'Ram', 'Rover',
        'Saturn', 'Subaru', 'Tesla', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['excellent', 'fair', 'good', 'like new', 'new', 'salvage'],
       dtype=object),
 array(['10 cylinders', '12 cylinders', '3 cylinders', '4 cylinders',
        '5 cylinders', '6 cylinders', '8 cylinders', 'other'], dtype=object),
 array(['diesel', 'electric', 'gas', 'hybrid', 'other'], dtype=object),
 array(['clean', 'lien', 'missing', 'parts only', 'rebuilt', 'salvage'],
       dtype=object),
 array(['automatic', 'manual', 'other'], dtype=object),
 array(['4wd', 'fwd', 'rwd']

In [68]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),
                                       ["manufacturer", "condition", "cylinders", "fuel",
                                        "title_status", "transmission", "drive" , "type", 
                                        "model", "state"]), remainder="passthrough")

In [69]:
lr=LinearRegression()

In [70]:
pipe=make_pipeline(column_trans,lr)

In [71]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Acura', 'Alfa-romeo', 'Aston-martin', 'Audi', 'Bmw', 'Buick',
       'Cadillac', 'Chevrolet', 'Chrysler', 'Datsun', 'Dodge', 'Ferrari',
       'Fiat', 'Ford', 'Gmc', 'Harley-davidson', 'Honda', 'Hyundai',
       'Infiniti', 'Jaguar', 'Jeep', 'Kia',...
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)]),
                                                  ['manufacturer', 'condition',
                                                   'cylinders', 'fuel',
                                             

In [72]:
y_pred=pipe.predict(x_test)

In [73]:
y_pred

array([ 8202.1698792 , 15500.70533677, 12563.05765481, ...,
       22561.68944698, 35387.63488514, 16636.14278604])

In [74]:
# checking for r2 socre
r2_score(y_test, y_pred)

0.6131377309286132

In [75]:
print(sorted(Cars_df["state"].unique()))

['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']


In [76]:
#Cars_df.head()
Cars_df["state"].nunique()

50

In [77]:
# checking for maximum possible r2 scores
scores = []
for i in range(1000):
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train, y_train)
    y_pred=pipe.predict(x_test)
    #print(i, r2_score(y_test, y_pred))
    scores.append(r2_score(y_test, y_pred))

In [78]:
np.argmax(scores)

465

In [79]:
scores[np.argmax(scores)]

0.625293389815331

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(x_train, y_train)
y_pred=pipe.predict(x_test)
r2_score(y_test, y_pred)

0.625293389815331

In [81]:
import pickle

In [82]:
pickle.dump(pipe,open("LinearRegressionModel.pkl", "wb"))

In [83]:
Cars_df["model"].loc[Cars_df["manufacturer"]=="Ford"]

31             Ford F-150
55              Ford F250
63           Ford Mustang
65              Ford F450
76        Ford Expedition
               ...       
426766          Ford F350
426774    Ford Expedition
426776          Ford F250
426785          Ford F150
426792         Ford F350,
Name: model, Length: 28595, dtype: object

In [85]:
pipe.predict(pd.DataFrame([["2000", "Ford", "Ford F-150", "good", 
                            "6 cylinders", "gas", 90000, "clean", "automatic",
                            "fwd", "SUV", "Washington"]], 
                          columns=["year","manufacturer","model","condition",
                                   "cylinders","fuel","Distance_Traveled","title_status",
                                   "transmission","drive", "type", "state"]))

array([11173.02407328])